### ISSUE TITLE
i face with some problem when install environment

### ISSUE THREAD

**Issue by tobby2002** [OnGridSystems/CATEd#22]
dear this owner
i appreciate for this github CATEd
but i fade with some error like this....;

[2018/10/08 18:44:13] HTTP POST /trade/get_ticker/ 500 [0.06, 127.0.0.1:52104]
[2018/10/08 18:44:20] HTTP POST /trade/exchange_script_activity/ 200 [0.09, 127.0.0.1:52104]
[2018/10/08 18:44:20] HTTP GET /trade/setup/1/ 200 [0.05, 127.0.0.1:52104]
[2018/10/08 18:44:20] WebSocket DISCONNECT /trade/ [127.0.0.1:52108]
[2018/10/08 18:44:20] WebSocket HANDSHAKING /trade/ [127.0.0.1:52112]
[2018/10/08 18:44:20] WebSocket CONNECT /trade/ [127.0.0.1:52112]
Internal Server Error: /trade/get_ticker/
Traceback (most recent call last):
.......
.......
  File "/Users/neo/PycharmProjectPro/CATEd-master/venv/lib/python3.6/site-packages/MySQLdb/cursors.py", line 375, in _do_query
    db.query(q)
  File "/Users/neo/PycharmProjectPro/CATEd-master/venv/lib/python3.6/site-packages/MySQLdb/connections.py", line 276, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'portal_ticker.ticker_app_exchangeticker' doesn't exist")
[2018/10/08 18:44:20] HTTP POST /trade/get_ticker/ 500 [0.09, 127.0.0.1:52104]

like upper error message 
when i enter this page 
<img width="1288" alt="2018-10-09 12 47 33" src="https://user-images.githubusercontent.com/7940014/46619421-0751d280-cb5d-11e8-8d04-46b5945c9322.png">

can you help me to solve for this error?

maybe i think this is caused by migration
of course, i did the followings;
------
echo "create database trade character set utf8; create database celery_result; create database portal_ticker;" | mysql -u root

And migrate

python manage.py migrate
Load initial data with some exchanges and wallets

python manage.py loaddata dump.json
Create you own superuser with

python manage.py createsuperuser
-----
even though i created 3database, 
but by migration process(i.e python manage.py migrate),
i could not make tables in each port_ticker and celery_result databases
like this image...
![points](https://user-images.githubusercontent.com/7940014/46619840-19804080-cb5e-11e8-8607-a93a38c87a7c.png)

please help me ^^

**Comment by achievement008** [comment]
Hi, sorry for so long.
The project uses several databases, this is visible if you open the settings file (default and portal_ticker). The command "python manage.py migrate" migrates only for the default database, the second one needs to be migrated separately (python manage.on migrate ticker_app --database = portal_ticker).
Hope it helps =)
